### ISSUE TITLE
Your repository has an outdated version of the firmware!

### ISSUE THREAD

**Issue by juchong** [EverLand1/9300-8i_IT-Mode#1]
Hi! 

First, thank you for taking the time to write up such detailed instructions! It really made flashing my card much easier. However, it looks like your repository includes an old version of the firmware (v16.00.10.00). It's **very important** that users **not** use this version due to a reset bug present in previous versions of the 9300-xx firmwares. Here's a description of the issue from IX-Systems' website:

> Servers with the LSI 9300 HBA may experience some performance issues causing the controller to reset when
> using SATA HDDs.
> iXsystems has worked with Broadcom to provide a firmware update that resolves the controller reset issue. If
> you have the LSI 9300 HBA with firmware version 16.00.12.00 or earlier installed and would like to resolve the
> occasional controller reset from this issue, follow these instructions. Please note that the firmware update is
> only available from iXsystems.”
> Please Note: This problem only applies to firmware versions below 16.00.12.00 and only affects SATA drives.
> SAS drives are not affected.

[Link to the document](https://www.truenas.com/docs/files/LSI9300xxFirmwareUpdatev1_0.pdf)

I've personally encountered this bug on a previous server build and nearly lost all of my data because of it ([link](https://www.reddit.com/r/truenas/comments/18xylr6/reslivering_nightmare_followup_and_lessons_learned/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)).

The latest firmware (v16.00.12.00) for all card variants can be found [here](https://cdn.truenas.com/community/resources/lsi-9300-xx-firmware-update.145/history).

**Comment by EverLand1** [comment]
I appreciate the heads up! The new firmware has been added and the old firmware has been marked as deprecated. Thanks!

**Comment by ibramawalla2005-beep** [comment]
hey
